Remove /WX from CFLAGS for VC-WIN32 build
crypto\ec\oqs_meth.c generates warnings:

crypto\ec\oqs_meth.c(611): error C2220: warning treated as error - no 'object' file generated
crypto\ec\oqs_meth.c(611): warning C4018: '>': signed/unsigned mismatch
crypto\ec\oqs_meth.c(1006): warning C4018: '>': signed/unsigned mismatch

With /WX that causes a build break. VC-WIN64A does not use /WX, and this change removes it from VC-WIN32 to fix the build.